name: CI

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: make install-ci

      - name: Run lint
        run: make lint
